clone_depth: 30
environment:
  VisualStudioVersion: 14.0
configuration: Release
os: Visual Studio 2015
install:
  - ps: nuget install boost -o "${env:APPVEYOR_BUILD_FOLDER}"
  - ps: nuget install boost_unit_test_framework-vc140 -o "${env:APPVEYOR_BUILD_FOLDER}"
  - ps: nuget install boost_program_options-vc140 -o "${env:APPVEYOR_BUILD_FOLDER}"
  - ps: nuget install boost_random-vc140 -o "${env:APPVEYOR_BUILD_FOLDER}"
  - ps: nuget install boost_serialization-vc140 -o "${env:APPVEYOR_BUILD_FOLDER}"
  - ps: nuget install boost_math_c99-vc140 -o "${env:APPVEYOR_BUILD_FOLDER}"
  - ps: nuget install OpenBLAS -o "${env:APPVEYOR_BUILD_FOLDER}"
build_script:
  - mkdir boost_libs
  - ps: cp C:\projects\mlpack\boost_program_options-vc140.1.60.0.0\lib\native\address-model-64\lib\*.* C:\projects\mlpack\boost_libs\
  - ps: cp C:\projects\mlpack\boost_math_c99-vc140.1.60.0.0\lib\native\address-model-64\lib\*.* C:\projects\mlpack\boost_libs\
  - ps: cp C:\projects\mlpack\boost_random-vc140.1.60.0.0\lib\native\address-model-64\lib\*.* C:\projects\mlpack\boost_libs\
  - ps: cp C:\projects\mlpack\boost_serialization-vc140.1.60.0.0\lib\native\address-model-64\lib\*.* C:\projects\mlpack\boost_libs\
  - ps: cp C:\projects\mlpack\boost_unit_test_framework-vc140.1.60.0.0\lib\native\address-model-64\lib\*.* C:\projects\mlpack\boost_libs\
  - appveyor DownloadFile http://sourceforge.net/projects/arma/files/armadillo-6.500.5.tar.gz
  - 7z x armadillo-6.500.5.tar.gz -so | 7z x -si -ttar > nul
  - ps: (gc .\armadillo-6.500.5\include\armadillo_bits\config.hpp).replace("// #define ARMA_64BIT_WORD","#ifdef _WIN64`r`n#define ARMA_64BIT_WORD`r`n#else`r`n#define ARMA_32BIT_WORD`r`n#endif") | sc .\armadillo-6.500.5\include\armadillo_bits\config.hpp
  - cd armadillo-6.500.5 && mkdir build && cd build
  - cmake -G "Visual Studio 14 2015 Win64" -DBLAS_LIBRARY:FILEPATH="%APPVEYOR_BUILD_FOLDER%/OpenBLAS.0.2.14.1/lib/native/lib/x64/libopenblas.dll.a" -DLAPACK_LIBRARY:FILEPATH="%APPVEYOR_BUILD_FOLDER%/OpenBLAS.0.2.14.1/lib/native/lib/x64/libopenblas.dll.a" -DCMAKE_PREFIX:FILEPATH="%APPVEYOR_BUILD_FOLDER%/armadillo" -DBUILD_SHARED_LIBS=OFF ..
  - '"C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe" "C:\projects\mlpack\armadillo-6.500.5\build\armadillo.sln" /m /verbosity:quiet /p:Configuration=Release;Platform=x64'
  - cd C:\projects\mlpack && mkdir build && cd build
  - cmake -G "Visual Studio 14 2015 Win64" -DBLAS_LIBRARY:FILEPATH="%APPVEYOR_BUILD_FOLDER%/OpenBLAS.0.2.14.1/lib/native/lib/x64/libopenblas.dll.a" -DLAPACK_LIBRARY:FILEPATH="%APPVEYOR_BUILD_FOLDER%/OpenBLAS.0.2.14.1/lib/native/lib/x64/libopenblas.dll.a" -DARMADILLO_INCLUDE_DIR="C:/projects/mlpack/armadillo-6.500.5/include" -DARMADILLO_LIBRARY:FILEPATH="C:\projects\mlpack\armadillo-6.500.5\build\Debug\armadillo.lib" -DBOOST_INCLUDEDIR:PATH="C:\projects\mlpack\boost.1.60.0.0\lib\native\include" -DBOOST_LIBRARYDIR:PATH="C:\projects\mlpack\boost_libs" -DDEBUG=OFF -DPROFILE=OFF ..
  - '"C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe" "C:\projects\mlpack\build\mlpack.sln" /m /verbosity:normal /p:Configuration=Release;Platform=x64'
  - 7z a mlpack-windows-no-libs.zip "%APPVEYOR_BUILD_FOLDER%\build\Release\*.exe"
  - 7z a mlpack-windows.zip "%APPVEYOR_BUILD_FOLDER%\build\Release\*.*" "%APPVEYOR_BUILD_FOLDER%/OpenBLAS.0.2.14.1/lib/native/lib/x64/*.*"

artifacts:
  - path: '**\*.zip'

notifications:
- provider: Email
  to:
  - mlpack-git@cc.gatech.edu
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true

# All plans have maximum build job execution time of 60 minutes. But right, now
# the machine takes 30 minutes to build the code and at least 50 minutes to run
# all tests.
# test_script:   -
# '"C:\projects\mlpack\build\Release\mlpack_test.exe" -p'
