sudo: required
dist: xenial
language: cpp

env:
  - CMAKE_OPTIONS="-DDEBUG=OFF -DPROFILE=OFF -DPYTHON=/usr/bin/python"
  - CMAKE_OPTIONS="-DDEBUG=ON -DPROFILE=OFF -DBUILD_PYTHON_BINDINGS=OFF"

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - export CC=gcc-4.8
  - export CXX=g++-4.8
  - printenv
  - sudo apt-get install libopenblas-dev && sudo apt-get install liblapack-dev
  - sudo apt-get install -qq g++-4.8 libboost1.54-all-dev
  - sudo pip install cython setuptools numpy pandas
  - curl http://masterblaster.mlpack.org:5005/armadillo-6.500.5.tar.gz | tar xvz && cd armadillo*
  - cmake . && make && sudo make install && cd ..
  - sudo cp .travis/config.hpp /usr/include/armadillo_bits/config.hpp

install:
  - mkdir build && cd build && cmake $CMAKE_OPTIONS .. && make -j2

script:
  - CTEST_OUTPUT_ON_FAILURE=1 travis_wait 30 ctest -j2

notifications:
  email:
    - mlpack-git@lists.mlpack.org
  irc:
    channels:
      - "chat.freenode.net#mlpack"
    on_success: change
    on_failure: always
