language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
      env: CMAKE_OPTIONS="-DDEBUG=OFF -DPROFILE=OFF -DPYTHON_EXECUTABLE=/usr/bin/python"
      before_install:
        - sudo apt-get update
        - sudo apt-get install -y --allow-unauthenticated libopenblas-dev liblapack-dev g++ libboost-all-dev python-pip cython python-numpy python-pandas
        - sudo pip install --upgrade --ignore-installed setuptools cython
        - curl https://ftp.fau.de/macports/distfiles/armadillo/armadillo-6.500.5.tar.gz | tar xvz && cd armadillo*
        - cmake . && make && sudo make install && cd ..
        - sudo cp .travis/config.hpp /usr/include/armadillo_bits/config.hpp

    - os: linux
      dist: xenial
      env: CMAKE_OPTIONS="-DDEBUG=OFF -DPROFILE=OFF -DPYTHON_EXECUTABLE=/usr/bin/python3"
      before_install:
        - sudo apt-get update
        - sudo apt-get install -y --allow-unauthenticated libopenblas-dev liblapack-dev g++ libboost-all-dev python3-pip cython3 python3-numpy
        - sudo pip3 install --upgrade --ignore-installed setuptools cython pandas
        - curl https://ftp.fau.de/macports/distfiles/armadillo/armadillo-6.500.5.tar.gz | tar xvz && cd armadillo*
        - cmake . && make && sudo make install && cd ..
        - sudo cp .travis/config.hpp /usr/include/armadillo_bits/config.hpp

    - os: linux
      dist: xenial
      env: CMAKE_OPTIONS="-DDEBUG=ON -DPROFILE=OFF -DBUILD_PYTHON_BINDINGS=OFF"
      before_install:
        - sudo apt-get update
        - sudo apt-get install -y --allow-unauthenticated libopenblas-dev liblapack-dev g++ libboost-all-dev
        - curl https://ftp.fau.de/macports/distfiles/armadillo/armadillo-6.500.5.tar.gz | tar xvz && cd armadillo*
        - cmake . && make && sudo make install && cd ..
        - sudo cp .travis/config.hpp /usr/include/armadillo_bits/config.hpp

    - os: osx
      osx_image: xcode9.4 # Maybe we can try some different ones?
      env: CMAKE_OPTIONS="-DDEBUG=ON -DPROFILE=OFF -DBUILD_PYTHON_BINDINGS=OFF"
      before_install:
        - brew install openblas armadillo || brew install openblas armadillo

install:
  - mkdir build && cd build && cmake $CMAKE_OPTIONS .. && travis_wait 75 make -j2

script:
  - CTEST_OUTPUT_ON_FAILURE=1 travis_wait 30 ctest -j2

notifications:
  email:
    - mlpack-git@lists.mlpack.org
  irc:
    channels:
      - "chat.freenode.net#mlpack"
    on_success: change
    on_failure: always
